services:
  db:
    image: surrealdb/surrealdb:latest
    container_name: butz-db
    ports:
      - 6969:8000
    volumes:
      - ./database:/database
    command: start --user root --pass root file:/database
