GET localhost:8001/users

###

GET localhost:8001/users/users:rcjqf3dwbmj0wugkx08l

###

POST localhost:8001/users
Content-Type: application/x-user

{
"name":"beate",
"roles": 77
}

###

PUT localhost:8001/users/users:rcjqf3dwbmj0wugkx08l
Content-Type: application/x-user

{
"name":"nina",
"roles":1
}

###